config/routes.rb
Rails.application.routes.draw do
  get 'jsonstring/view'
  root "table#view"
  get 'table/view'
  post 'table/reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  include ActiveModel::Attributes

  attribute :counter, :integer, default: 0
  validates :counter, presence: true

end

app/models/key.rb
class Key < ApplicationRecord

end

app/models/new_item.rb
class NewItem < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jsonstring_controller.rb
class JsonstringController < ApplicationController
  def view
    @msg = {"message":"Hello World!"}
    render json: @msg
  end
end

app/controllers/table_controller.rb
class TableController < ApplicationController
  def view
    record = Key.find_by(params[:id])
    if record = nil
      record.create(key: 1)
      redirect_to root_path
    else
      record = Key.last
      viewValue = record ? record.key + 1 : 1
      add = Key.create(key: viewValue)
      return add
      redirect_to table_view_path
    end
  end

  def reset
    record = Key.last
    viewValue = record ? 0 : record.key
    Key.create(key: viewValue)
    redirect_to table_view_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jsonstring_helper.rb
module JsonstringHelper
end

app/helpers/table_helper.rb
module TableHelper
end

app/views/jsonstring/view.html.erb
<h1>Jsonstring#view</h1>
<p>Find me in app/views/jsonstring/view.html.erb</p>
<%= @msg %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransactionTable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/table/view.html.erb
<h1>Table#view</h1>
<p>Find me in app/views/table/view.html.erb</p>

<h1>Page Views: <%= Key.last.key %></h1>

<%= form_with url: table_reset_path, method: :post do |f| %>
  <%= f.submit "Reset Counter" %>
<% end %>